AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: journal-officiel-scrapper

Globals:
  Function:
    Timeout: 90
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  JournalOfficielScrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: journal-officiel-scrapper
      Description: Lambda used to collect Journal Officiel datas.
      PackageType: Image
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/journal-officiel:journal-officiel-v1
      Environment:
        Variables:
          dynamodb_table_name: "journal-officiel"
          datalake_s3_bucket_name: "journal-officiel-datalake"
    Metadata:
      DockerTag: journal-officiel-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
    Policies:
      - DynamoDBWritePolicy:
          TableName:
            "journal-officiel"
      - S3WritePolicy:
          Bucketname:
            "journal-officiel-datalake"
    Tags:
      application: "journal-officiel"
      environment: "production"